### PR TITLE
symbiotic2cs: produce <unknown> rather than <Unknown>

### PR DESCRIPTION
**Pull request by kdudka**
... to make the output compatible with other tools supported by csdiff

Related: https://github.com/csutils/csdiff/issues/37

### CODE REVIEW

**Review by lzaoral — APPROVED** [review]
That's very reasonable. Thanks!

**Comment by lzaoral** [comment]
I''ll merge this and rebuild the package after the following upstream-related issue is resolved:
```
Cloning into '/home/lukas/rpm-symbiotic/srpm/symbiotic/sbt-slicer'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: clone of 'git://github.com/staticafi/sbt-slicer' into submodule path '/home/lukas/rpm-symbiotic/srpm/symbiotic/sbt-slicer' failed
Failed to clone 'sbt-slicer'. Retry scheduled
```

**Comment by lzaoral** [comment]
Cloning-fix upstream PR: https://github.com/staticafi/symbiotic/pull/219

**Comment by kdudka** [comment]
@lzaoral Thank you for taking care of it!

**Comment by lzaoral** [comment]
COPR build: https://copr.fedorainfracloud.org/coprs/g/aufover/symbiotic/build/3915410/

**Pull request merged**
